import { readdir } from 'node:fs/promises';
import { extname, join } from 'node:path';
import { pathToFileURL } from 'node:url';
import type { WorkflowEngine } from './engine.js';
import { type WorkflowClass, type WorkflowMeta, workflowMeta } from './workflow-ref.js';

/** A discovered workflow class plus its resolved {@link WorkflowMeta} — from a `BaseWorkflow`
 *  subclass's `static workflow` config. */
export interface DiscoveredWorkflow {
  meta: WorkflowMeta;
  cls: WorkflowClass;
}

/**
 * Register a single workflow class on the engine — a `BaseWorkflow` subclass (its `static workflow`
 * config), resolved via {@link workflowMeta}. Instantiates it once and binds its `run(ctx, input)`
 * as the workflow body via `engine.register`. The low-level `engine.register(name, version, fn)`
 * stays the escape hatch — this is the convenience the `app/workflows` convention builds on. No-op
 * (returns `false`) for a non-workflow class (no `static workflow` config).
 */
export function registerWorkflowClass(engine: WorkflowEngine, cls: unknown): boolean {
  const meta = workflowMeta(cls);
  if (!meta) return false;
  const Ctor = cls as new () => { run(ctx: unknown, input: unknown): Promise<unknown> | unknown };
  const instance = new Ctor();
  engine.register(
    meta.name,
    meta.version,
    (ctx, input) => Promise.resolve(instance.run(ctx, input)),
    {
      ...(meta.tags ? { tags: meta.tags } : {}),
      ...(meta.executionTimeout !== undefined ? { executionTimeout: meta.executionTimeout } : {}),
      ...(meta.onEvent ? { onEvent: meta.onEvent } : {}),
    },
  );
  return true;
}

/**
 * Pick the module extension for the running environment so a built app (`.js`) and a dev/ts app
 * (`.ts`, run under a loader) never double-register the same workflow. We import only files whose
 * extension matches `import.meta.url`'s own (`.ts` when running from source, `.js` from `dist`),
 * which keeps scanner and `make:workflow` (it scaffolds `.ts`) in agreement under both setups.
 */
const MODULE_EXT = extname(import.meta.url || '') === '.ts' ? '.ts' : '.js';

/**
 * Scan a directory RECURSIVELY for modules and collect every exported workflow class — a
 * `BaseWorkflow` subclass (the default export and any named export are considered) — so nested
 * conventions like
 * `app/workflows/billing/charge_workflow.ts` are found, matching `make:workflow`'s nested-path
 * scaffolding. Only the environment-appropriate extension is imported (see {@link MODULE_EXT}), and
 * each module path is visited once, so a built `.js` and a dev `.ts` of the same module never both
 * register. Missing directory → empty list (the convention is opt-in: no `app/workflows`, nothing to
 * register).
 */
export async function discoverWorkflows(dir: string): Promise<DiscoveredWorkflow[]> {
  let entries: string[];
  try {
    entries = await readdir(dir, { recursive: true });
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return [];
    throw err;
  }

  const found: DiscoveredWorkflow[] = [];
  const seen = new Set<unknown>();
  for (const entry of entries.sort()) {
    if (extname(entry) !== MODULE_EXT || entry.endsWith(`.d${MODULE_EXT}`)) continue;
    const mod = (await import(pathToFileURL(join(dir, entry)).href)) as Record<string, unknown>;
    for (const exported of Object.values(mod)) {
      if (seen.has(exported)) continue;
      const meta = workflowMeta(exported);
      if (!meta) continue;
      seen.add(exported);
      found.push({ meta, cls: exported as WorkflowClass });
    }
  }
  return found;
}

/**
 * Discover every workflow class (`BaseWorkflow` subclass) under `dir` and register each on the
 * engine. Returns the registered metadata so the caller can log what was wired.
 * Best-effort over a missing directory.
 */
export async function registerWorkflowsFromDir(
  engine: WorkflowEngine,
  dir: string,
): Promise<WorkflowMeta[]> {
  const discovered = await discoverWorkflows(dir);
  for (const { cls } of discovered) registerWorkflowClass(engine, cls);
  return discovered.map((d) => d.meta);
}

/**
 * The shape of the build-time barrel generated by the Assembler `init` hook
 * (`@adonis-agora/durable/hooks/workflows`): a map of stable key → lazy module import, e.g.
 * `{ Charge: () => import('#workflows/charge_workflow') }`. The exact key is irrelevant here — we
 * register every workflow export of every module (`BaseWorkflow` subclass), identical to the runtime
 * scan.
 */
export type WorkflowsBarrel = Record<string, () => Promise<Record<string, unknown>>>;

/**
 * Register every workflow class reachable from a generated {@link WorkflowsBarrel} (`BaseWorkflow`
 * subclass), by awaiting each lazy module import and registering each
 * workflow export — the build-time equivalent of {@link registerWorkflowsFromDir}, with no runtime
 * `readdir`. Each module is imported once and each class registered once (deduped), so a class
 * re-exported from several modules is safe. Returns the registered metadata so the caller can log
 * what was wired.
 */
export async function registerWorkflowsFromBarrel(
  engine: WorkflowEngine,
  barrel: WorkflowsBarrel,
): Promise<WorkflowMeta[]> {
  const registered: WorkflowMeta[] = [];
  const seen = new Set<unknown>();
  for (const load of Object.values(barrel)) {
    const mod = await load();
    for (const exported of Object.values(mod)) {
      if (seen.has(exported)) continue;
      const meta = workflowMeta(exported);
      if (!meta) continue;
      seen.add(exported);
      registerWorkflowClass(engine, exported);
      registered.push(meta);
    }
  }
  return registered;
}
